run:
	python2 gridworld.py -a value -i 100 -k 10
	python2 gridworld.py -a value -i 100 -g BridgeGrid --discount 0.9 --noise 0.2
	python2 gridworld.py -a q -k 5 -m
	python2 gridworld.py -a q -k 100 
	python2 crawler.py
	python2 pacman.py -p PacmanQAgent -x 2000 -n 2010 -l smallGrid 
	python2 pacman.py -p PacmanQAgent -n 10 -l smallGrid -a numTraining=10
